[package]
name = "telegram-message-source"
version = "1.1.3"

authors = ["Itsusinn <itsusinn@foxmail.com>"]
edition = "2018"

[dependencies]
# bot
teloxide ={ version = "0.5.3",default-features = false,features = ["frunk", "macros", "auto-send","ctrlc_handler","rustls"] }
teloxide-core = { version = "0.3.3",default-features = false, features = ["rustls"] }
teloxide-macros  = "0.4.1"

# logging
env_logger = "0.9.0"
log = "0.4.14"

# serialization
serde = { version = "1.0.130",default-features = false,features = ["derive","rc"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"

# asynchronous
async-std = "1.10.0"
tokio = { version =  "1.15.0",default-features = false,features = ["rt-multi-thread", "macros","signal"] }
tokio-util = "0.6.8"
tokio-stream = "0.1.7"
smol = "1.2.5"
futures = "0.3.17"

# error handling
thiserror = "1.0.30"
anyhow = "1.0.44"

# encoding and decoding
base64 = "0.13.0"

# crypto
aes-gcm = {version = "0.9.4",features = ["std"]}

# tools
url = "2.2.2"
dashmap = { version = "5.0.0",features = ["serde"] }
once_cell = "1.8.0"
educe = "0.4.18"
num-bigint = "0.4.2"
arcstr = { version = "1.1.1", features = ["serde"] }
bytes = { version = "1.1.0", features = ["serde"] }

# webhook
warp = "0.3.1"

# http
reqwest = { version = "0.11.9" ,default-features = false ,features = ["rustls","socks","rustls-tls-webpki-roots","stream","multipart"] }

# database
sled = "0.34.7"

# mesagisto
nats = "0.16.0"
mesagisto-client = { branch = "master", git = "https://github.com/MeowCat-Studio/mesagisto-client-rs.git"}
# mesagisto-client = { path = "../../mesagisto-client/rust" }
automatic-config = { git = "https://github.com/Itsusinn/automatic-config-rs.git" }
singleton = { git = "https://github.com/Itsusinn/singleton-rs.git", rev = "bee321c" }
# singleton = { path = "/home/itsusinn/Workspace/Code/singleton-rs" }
either = "1.6.1"
# hex = "0.4"
base64-url = "1.4.10"

[dependencies.pyo3]
version = "0.15.1"
optional = true
features = ["auto-initialize"]

[features]
# default = ["yinglish"]
yinglish = ["pyo3"]
