[package]
name = "telegram-message-source"
version = "1.5.3"

authors = ["Itsusinn <itsusinn@foxmail.com>"]
edition = "2021"

[features]
default = ["color"]
no-color = ["colored/no-color"]
color = ["tracing-subscriber/ansi"]

[dependencies]
# bot
teloxide = { version = "0.9.2", default-features = false, features = ["macros", "auto-send","ctrlc_handler","rustls","nightly"] }
teloxide-core = { version = "0.6.3", default-features = false, features = ["rustls","cache_me"] }
teloxide-macros = "0.6.2"

# logging
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", default-features = false, features = ["tracing-log", "std", "local-time","fmt"] }
colored = "2.0.0"
time = { version = "0.3.11", features = ["macros", "local-offset"] }

# serialization
serde = { version = "1.0.138", default-features = false, features = ["derive","rc"] }
serde_json = "1.0.82"
serde_yaml = "0.8.24"

# asynchronous
tokio = { version = "1.19.2", default-features = false, features = ["macros","signal","rt-multi-thread"] }
tokio-util = "0.7.3"
tokio-stream = "0.1.9"
futures = "0.3.21"
async-trait = "0.1.56"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls","rustls-tls-native-roots","stream","multipart"] }

# error handling
thiserror = "1.0.31"
anyhow = "1.0.58"

# encoding and decoding
base64-url = "1.4.13"
# hex = "0.4"

# crypto
aes-gcm = { version = "0.9.4", features = ["std"] }

# tools
dashmap = { version = "5.3.4", features = ["serde"] }
once_cell = "1.12.0"
educe = { version = "0.4.19", default-features = false, features = ["Default"] }
arcstr = { version = "1.1.4", features = ["serde"] }
yaml-rust = "0.4.5"
linked-hash-map = "0.5.6"
either = "1.7.0"
mime = "0.3.16"
infer = "0.9.0"

# database
sled = "0.34.7"

# mesagisto
nats = "0.21.0"
mesagisto-client = { branch = "master", git = "https://github.com/MeowCat-Studio/mesagisto-client-rs.git"}
# mesagisto-client = { path = "../../mesagisto-client/rust" }
automatic-config = { branch = "master", git = "https://github.com/Itsusinn/automatic-config-rs.git" }
# automatic-config = { path = "/code/automatic-config-rs" }
lateinit = { branch = "master", git = "https://github.com/Itsusinn/lateinit-rs.git" }
singleton = { branch="master", git = "https://github.com/Itsusinn/singleton-rs.git" }
# singleton = { path = "/code/singleton-rs" }

[profile.release]
opt-level = 'z'
debug = false
lto = true
incremental = false
codegen-units = 1
strip = true
