[package]
name = "telegram-message-source"
version = "1.0.4"

authors = ["Itsusinn <itsusinn@foxmail.com>"]
edition = "2018"

[dependencies]
# bot
teloxide ={ version = "0.5.2",default-features = false,features = ["frunk", "macros", "auto-send","ctrlc_handler","rustls"] }
teloxide-core = { version = "0.3.3",default-features = false, features = ["rustls"] }
teloxide-macros  = "0.4"

# logging
env_logger = "0.9.0"
log = "0.4.14"

# serialization
serde = { version = "1.0.130", features = ["derive","rc"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"

# asynchronous
async-std = "1.10.0"
tokio = { version =  "1.12.0", features = ["rt-multi-thread", "macros","signal"] }
tokio-util = "0.6.8"
tokio-stream = "0.1.7"
smol = "1.2.5"
futures = "0.3.17"

# error handling
thiserror = "1.0.30"
anyhow = "1.0.44"

# encoding and decoding
base64 = "0.13.0"

# crypto
aes-gcm = {version = "0.9.4",features = ["std"]}

# tools
url = "2.2.2"
dashmap = { version = "4.0.2" , features = ["serde"] }
once_cell = "1.8.0"
educe = "0.4.18"
num-bigint = "0.4.2"
arcstr = { version = "1.1.1", features = ["serde"] }
bytes = { version = "1.1.0", features = ["serde"] }

# webhook
warp = "0.3.1"

# http
reqwest = { version = "0.11.5" ,default-features = false ,features = ["rustls","socks","rustls-tls-webpki-roots","stream","multipart"] }

# database
sled = "0.34.7"

# mesagisto
nats = "0.15.2"
mesagisto-client = { path = "libs/mesagisto-client" }
automatic-config = { git = "https://github.com/Itsusinn/automatic-config-rs.git" }
singleton = { git = "https://github.com/Itsusinn/singleton-rs.git", rev = "bee321c" }
# singleton = { path = "/home/itsusinn/Workspace/Code/singleton-rs" }
either = "1.6.1"
# hex = "0.4"

[dependencies.pyo3]
version = "0.14.5"
optional = true
features = ["auto-initialize"]

[features]
# default = ["yinglish"]
yinglish = ["pyo3"]
