[package]
name = "telegram-mesaga-fonto"
version = "1.0.2"

authors = ["Itsusinn <itsusinn@foxmail.com>"]
edition = "2018"

[dependencies]
# bot
teloxide ={ version = "0.5.0",default-features = false,features = ["frunk", "macros", "auto-send","ctrlc_handler","rustls"] }
teloxide-core = { version = "0.3.2",default-features = false, features = ["rustls"] }
teloxide-macros  = "0.4.1"

# logging
env_logger = "0.9.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"

# serialization
serde = { version = "1.0", features = ["derive","rc"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"

# asynchronous
tokio = { version =  "1.3.0", features = ["rt-multi-thread", "macros","signal"] }
tokio-util = "0.6"
tokio-stream = "0.1"
futures = "0.3.13"
blocking = "1.0.2"

# error handling
thiserror = "1.0"
anyhow = "1.0"

# encoding and decoding
base64-url = "1.4.8"

# tools
typed-headers = "0.2.0"
url = "2.1.0"
dashmap = { version = "4.0" , features = ["serde"] }
once_cell = "1.8.0"
educe = "0.4.18"

# data
bytes = "1.0.1"

# webhook
warp = "0.3.0"
reqwest = { version = "0.11.4" ,default-features = false ,features = ["rustls"] }


nats = "0.10.1"
async-nats = "0.10.1"
